name: polymaker
author: Yusril Rapsanjani <yuranicorp@gmail.com>
version: 1.0.0-nullsafety.1
homepage: https://github.com/yusriltakeuchi/polymaker.git
description: Polymaker is a flutter package used to get a list of locations for polygon google maps
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  google_maps_flutter: '>=2.0.1 <=3.0.0'
  geolocator: '>=7.0.1 <=8.0.0'
  provider: '>=5.0.0 <=6.0.0'
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - images/
    - assets/map_style.txt
