name: polymaker
# author: Yusril Rapsanjani <yuranicorp@gmail.com>
version: 1.0.3
homepage: https://github.com/yusriltakeuchi/polymaker.git
description: Polymaker is a flutter package used to get a list of locations for polygon google maps
environment:
  sdk: '>=2.12.0 <3.13.8'
  flutter: ">=1.17.0"
dependencies:
  google_maps_flutter: '>=2.0.1 <=3.0.0'
  geolocator: ^10.1.0
  provider: '>=5.0.0 <=7.0.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - images/
    - assets/map_style.txt
